# Generated by Django 4.1.10 on 2024-04-14 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Questions", "0001_initial"),
        ("Users", "0002_patient_groups_patient_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_response", models.TextField(blank=True, null=True)),
                ("numeric_response", models.IntegerField(blank=True, null=True)),
                ("bool_response", models.BooleanField(blank=True, null=True)),
                (
                    "emoji_response",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.patient"
                    ),
                ),
            ],
        ),
    ]
