# Generated by Django 4.1.10 on 2024-04-14 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("EMOJI", "Emoji"),
                            ("RATING", "Rating"),
                            ("YES_NO_MAYBE", "Yes/No/Maybe"),
                            ("TEXT", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
